Resources:
  WorkshopCdkTsQueue8E0ED440:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: WorkshopCdkTsStack/WorkshopCdkTsQueue/Resource
  WorkshopCdkTsQueuePolicy84162715:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: WorkshopCdkTsTopic3DAD1C1F
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Resource:
              Fn::GetAtt:
                - WorkshopCdkTsQueue8E0ED440
                - Arn
        Version: "2012-10-17"
      Queues:
        - Ref: WorkshopCdkTsQueue8E0ED440
    Metadata:
      aws:cdk:path: WorkshopCdkTsStack/WorkshopCdkTsQueue/Policy/Resource
  WorkshopCdkTsQueueWorkshopCdkTsStackWorkshopCdkTsTopic22A55DE46959D48A:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint:
        Fn::GetAtt:
          - WorkshopCdkTsQueue8E0ED440
          - Arn
      Protocol: sqs
      TopicArn:
        Ref: WorkshopCdkTsTopic3DAD1C1F
    DependsOn:
      - WorkshopCdkTsQueuePolicy84162715
    Metadata:
      aws:cdk:path: WorkshopCdkTsStack/WorkshopCdkTsQueue/WorkshopCdkTsStackWorkshopCdkTsTopic22A55DE4/Resource
  WorkshopCdkTsTopic3DAD1C1F:
    Type: AWS::SNS::Topic
    Metadata:
      aws:cdk:path: WorkshopCdkTsStack/WorkshopCdkTsTopic/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1WOywrCMBBFv8V9OrYiguv+gLbupU0iTFuTNpMoEvLv5gGCm5lzDxdmDnCuod4Nb6q4mKsFR/C9HfjMorp72gj81UknWftQBfK86AX55ydLDIxU7PduJG5wtahVavzlm16RJ5shhISdJO0MzzdarQSmZmBKCwkT7V/NCZpj/HIixMo4ZfEpoSv7C3+c2zHBAAAA
    Metadata:
      aws:cdk:path: WorkshopCdkTsStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

